version: '3.8'

services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: nest-api
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT:-3000}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-10d}
      SALT_ROUNDS: ${SALT_ROUNDS:-10}
      APP_NAME: ${APP_NAME:-short-links-api}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge